### ISSUE TITLE
future chat bubbles appear before loading

### ISSUE THREAD

**Issue by lenachen813** [moates/onlyBans#42]
Bubbles already present before the text is being typed.

<img width="1280" alt="Screen Shot 2022-12-20 at 3 28 15 PM" src="https://user-images.githubusercontent.com/77164713/208785608-10609c2f-7bad-44e4-8ba4-0ce815a11782.png">
<img width="1280" alt="Screen Shot 2022-12-20 at 3 29 20 PM" src="https://user-images.githubusercontent.com/77164713/208785704-65616fc3-e0af-4c70-a71c-2c569b625894.png">

**Comment by moates** [comment]
duplicate of #37
