### ISSUE TITLE
setting on/off toggle doesn't always work

### ISSUE THREAD

**Issue by shrlyhe** [moates/onlyBans#43]
when clicking the side panel settings options, and changing the sound and accessibility options from on to off and vice versa, sometimes the settings don't apply

example:
going from off to on for background videos and animations doesn't fully work

https://user-images.githubusercontent.com/15842725/217918544-5ea8ec30-c74b-4532-acb3-e93863bec358.mov

**Comment by moates** [comment]
For loading video/animation, you'll need to refresh the page to load them! I don't think this is a bug, but I'll add a note in the setting to clarify.
