### ISSUE TITLE
update Credits/Acknowledgements

### ISSUE THREAD

**Issue by moates** [moates/onlyBans#45]
- [x] add Web Baby Shirley
- [x] add Ack for Decoding Stigma

**Comment by shrlyhe** [comment]
PR here: https://github.com/moates/onlyBans/pull/46

**Comment by moates** [comment]
still missing names from the Decoding Stigma workshop!

**Comment by moates** [comment]
changed it to a generic ackwnoledgement since we didn't hear back from everyone.  :\ will do for now.
