### ISSUE TITLE
work on new final game ending

### ISSUE THREAD

**Issue by shrlyhe** [moates/onlyBans#47]
work on the new game ending according to this [doc](https://docs.google.com/document/d/1l-8hNyeJpfQLIfbE_sJqkIwzN-3hs830hxRLQ4vqWAE/edit)

- can modify `money-ending`, `got-money-ending`, `not-enough-money` to fit narrative
- add additional passages to continue story

**Comment by moates** [comment]
fyi I worked on the input for spell-to-uncurse a bit! Added $ritualOffering as variable in StoryInit and broke up the passages a bit. You can also click on "one" here to cycle through some options. But now she's all yours to figure out some creative ideas for the ritual animations. 

![image](https://user-images.githubusercontent.com/7770184/236369899-f4609249-08d1-4d1f-990d-17ebf31af7e9.png)

**Comment by moates** [comment]
Code review tip @shrlyhe , in spell-to-uncurse (now start-spell), there's a few broken emojis. Apple does an annoying thing where they sometimes make custom emojis that haven't rolled out to all platforms/browsers yet. A good way to check how emojis will display on different platforms is to use [Emojipedia](https://emojipedia.org/)



![image](https://user-images.githubusercontent.com/7770184/236370359-37b84475-8e2f-4540-95e8-660dc3a37a02.png)
